version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "9008:15672"
    - "5672:5672"
    - "5671:5671"
    environment: 
    - "RABBITMQ_DEFAULT_PASS=malwarescan"
    - "RABBITMQ_DEFAULT_USER=malwarescan"
    - "RABBITMQ_DEFAULT_VHOST=malwarescan"
    network_mode: malware_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
  app:
    image: "lbahtarliev/malwarescan:latest"
    environment:
    - "CAS_HOST=10.11.12.13:8082"
    - "CAS_KEY=63da075f599a42zxvlru97bb1dzd0dalf6f9ee65e10e"
    - "CAS_WAIT=0"
    - "DB_TYPE=sqlite"
    - "DB_HOST=localhost"
    - "DB_PORT=5432"
    - "DB_USER=malwarescan"
    - "DB_PASS=malwarescan"
    - "DB_NAME=malwarescan_db"
    - "CELERY_BROKER_URL=amqp://malwarescan:malwarescan@rabbitmq:5672/malwarescan"
    ports:
    - "8080:8080"
    network_mode: malware_network
    depends_on:
    - "rabbitmq"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
networks:
  malware_network:
    driver: overlay
